[package]
name = "data_pipeline_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "4.3", features = ["chrono"] }
csv = "1.3.1"
parquet = { version = "55.1.0", features = ["arrow"] }
arrow = { version = "55.1.0" }
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.17", features = ["v4", "serde"] }
chrono = "0.4.41" # fake's chrono feature might pull this in, but explicit is fine 
rand = "0.8"
